# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "rails"

gem "puma"
gem "sidekiq-delay_extensions", path: ".."
gem "redis-client"
gem "sqlite3"

gem "after_commit_everywhere"
